import { TutorialStep } from '.'

export const APPOINTMENTS_TUTORIALS: TutorialStep[] = [
  {
    target: 'appointments-menu',
    content:
      'Para finalizar el tutorial vamos a crear tu primera cita. Vamos directamente a "Citas".',
    title: 'Crear una Cita',
    placement: 'right',
    disableBeacon: false,
    showProgress: true,
    showSkipButton: true,
  },
  {
    target: 'add-appointment-button',
    content: 'Ahora, haz clic en este botón para empezar a crear una cita.',
    title: 'Crear Cita',
    placement: 'bottom',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/appointments',
    triggerAction: {
      type: 'open-modal',
      selector: '[data-tutorial="add-appointment-button"]',
      delay: 500,
      waitForModal: true,
    },
  },
  {
    target: 'appointment-customer-select',
    content:
      'Haz clic en el campo "Cliente", busca uno existente escribiendo el nombre o crea mediante el botón "Crear nuevo cliente" para la cita.',
    title: 'Definir Cliente para la Cita',
    placement: 'top',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/appointments',
    spotlightClicks: true,
    // subSteps: {
    //   triggerSelector: '[data-tutorial="create-new-customer-button"], [data-tutorial="create-new-customer-button-empty"]',
    //   modalSelector: '[role="dialog"]',
    //   steps: [
    //     {
    //       target: 'customer-first-name',
    //       content: 'Ingresa el nombre del cliente.',
    //       title: 'Nombre del Cliente',
    //       placement: 'top',
    //       disableBeacon: true,
    //       showProgress: true,
    //       showSkipButton: true,
    //     },
    //     {
    //       target: 'customer-last-name',
    //       content: 'Ingresa el apellido del cliente (opcional).',
    //       title: 'Apellido del Cliente',
    //       placement: 'top',
    //       disableBeacon: true,
    //       showProgress: true,
    //       showSkipButton: true,
    //     },
    //     {
    //       target: 'customer-email',
    //       content: 'Ingresa el correo electrónico del cliente.',
    //       title: 'Correo Electrónico',
    //       placement: 'top',
    //       disableBeacon: true,
    //       showProgress: true,
    //       showSkipButton: true,
    //     },
    //     {
    //       target: 'customer-phone',
    //       content: 'Ingresa el teléfono del cliente (opcional).',
    //       title: 'Teléfono del Cliente',
    //       placement: 'top',
    //       disableBeacon: true,
    //       showProgress: true,
    //       showSkipButton: true,
    //     },
    //     {
    //       target: 'customer-create-button',
    //       content: 'Haz clic para crear el cliente y continuar con la cita.',
    //       title: 'Crear Cliente',
    //       placement: 'top',
    //       disableBeacon: true,
    //       showProgress: true,
    //       showSkipButton: true,
    //     },
    //   ],
    //   onComplete: 'close-modal',
    // },
  },
  {
    target: 'appointment-service-select',
    content:
      'Selecciona uno o más servicios para esta cita. Y dependiendo de los servicios, podrás asignar especialistas por servicio si lo deseas. En este punto tendrás alertas de stock limitado o agotado en servicios con insumos asociados. Finalmente en cada servicio seleccionado podrás asignar un precio especial para esta cita en caso de ser necesario.',
    title: 'Servicios para la Cita',
    placement: 'top',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/appointments',
    spotlightClicks: true,
  },
  {
    target: 'appointment-date-picker',
    content:
      'Selecciona la fecha para la cita. Esto validará de forma inteligente la disponibilidad de los profesionales.',
    title: 'Fecha para la Cita',
    placement: 'top',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/appointments',
    spotlightClicks: true,
  },
  {
    target: 'appointment-specialist-selection',
    content:
      'Ahora, selecciona el especialista que realizará el servicio en esta cita.',
    title: 'Elige el Especialista',
    placement: 'top',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/appointments',
    spotlightClicks: true,
  },
  {
    target: 'appointment-specialist-time-slots',
    content:
      'Selecciona el horario disponible para el especialista en la fecha elegida.',
    title: 'Horario del Especialista',
    placement: 'top',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/appointments',
    spotlightClicks: true,
  },
  {
    target: 'save-appointment-button',
    content:
      '¡Buen Trabajo! Si el número del cliente es válido recibirá una notificación por WhatsApp. Haz clic en "Crear" para guardar tu cita y completar el tutorial.',
    title: 'Guardar Cita',
    placement: 'top',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/appointments',
    spotlightClicks: true,
    triggerAction: {
      type: 'click',
      selector: '[data-tutorial="save-appointment-button"]',
      delay: 500,
      waitForModal: false,
    },
  },
  {
    target: 'appointments-menu',
    content:
      '¡Felicidades! Has completado los pasos para crear tu primer cita.',
    title: '¡Cita Completada!',
    placement: 'right',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/appointments',
  },
]
