import { TutorialStep } from '.'

export const SPECIALIST_TUTORIALS: TutorialStep[] = [
  {
    target: 'specialists-menu',
    content:
      'Ahora vamos a crear tu primer especialista. Haz clic en "Especialistas" en el menú lateral y luego "Equipo.',
    title: 'Crear un Especialista',
    placement: 'right',
    disableBeacon: false,
    showProgress: true,
    showSkipButton: true,
  },
  {
    target: 'add-specialist-button',
    content: 'Aquí puedes agregar nuevo especialista.',
    title: 'Agregar Nuevo Especialista',
    placement: 'bottom',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/specialists/team',
    triggerAction: {
      type: 'open-modal',
      selector: '[data-tutorial="add-specialist-button"]',
      delay: 500,
      waitForModal: true,
    },
  },
  {
    target: 'specialist-name-input',
    content: 'Aquí defines los nombres.',
    title: 'Nombres del Especialista',
    placement: 'top',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/specialists/team',
    spotlightClicks: true,
  },
  {
    target: 'specialist-last-name-input',
    content: 'Aquí defines los apellidos.',
    title: 'Apellidos del Especialista',
    placement: 'top',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/specialists/team',
    spotlightClicks: true,
  },
  {
    target: 'specialist-email-input',
    content: 'Aquí defines los apellidos.',
    title: 'Correo del Especialista',
    placement: 'top',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/specialists/team',
    spotlightClicks: true,
  },
  {
    target: 'specialist-phone-input',
    content: 'Escriba el teléfono del especialista.',
    title: 'Teléfono del Especialista',
    placement: 'top',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/specialists/team',
    spotlightClicks: true,
  },
  {
    target: 'specialist-password-input',
    content:
      'Esta será la contraseña para que el especialista pueda acceder al sistema. Puedes copiarla y enviársela luego.',
    title: 'Contraseña de Acceso',
    placement: 'top',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/specialists/team',
    spotlightClicks: true,
  },
  {
    target: 'specialist-category-select',
    content:
      'Selecciona la categoría que mejor describe tu servicio. Esto ayudará a tus clientes a encontrarlo y a asociar con el especialista.',
    title: 'Servicios que realiza el Especialista',
    placement: 'top',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/specialists/team',
    spotlightClicks: true,
  },
  {
    target: 'specialist-photo-upload',
    content:
      'Sube una foto para que los clientes puedan identificar al especialista fácilmente.',
    title: 'Foto del Especialista',
    placement: 'top',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/specialists/team',
    spotlightClicks: true,
  },
  {
    target: 'specialist-bio',
    content:
      'Crea una breve descripción de tu especialidad. Describe la especialidad para que los clientes sepan en qué es experto.',
    title: 'Breve Descripción del Especialista',
    placement: 'top',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/specialists/team',
    spotlightClicks: true,
  },
  {
    target: 'save-specialist-button',
    content: '¡Excelente! Guarda tu especialista para finalizar el tutorial.',
    title: 'Guardar Servicio',
    placement: 'top',
    disableBeacon: true,
    showProgress: true,
    showSkipButton: true,
    page: '/admin/specialists/team',
    triggerAction: {
      type: 'click',
      selector: '[data-tutorial="save-specialist-button"]',
      delay: 500,
      waitForModal: false,
    },
  },
]
